# Generated by Django 5.1.6 on 2025-02-21 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
