# Generated by Django 5.1.6 on 2025-03-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='cate',
            new_name='categorys',
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='lesson/%Y/%M'),
        ),
    ]
