# Generated by Django 5.1.6 on 2025-03-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_rename_cate_course_categorys_alter_course_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='categorys',
            new_name='cate',
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='courses/%y/%m'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
