# Generated by Django 5.1.6 on 2025-03-14 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_rename_categorys_course_cate_alter_course_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.basemodel')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            bases=('courses.basemodel',),
        ),
    ]
