# Generated by Django 5.1.6 on 2025-03-14 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='less',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='courses.lesson'),
            preserve_default=False,
        ),
    ]
