# Generated by Django 5.1.6 on 2025-03-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_tag_less'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='less',
        ),
        migrations.AddField(
            model_name='lesson',
            name='tags',
            field=models.ManyToManyField(to='courses.tag'),
        ),
    ]
